name: mangas-api-container

services:
    mangas_api_db:
        image: bitnami/postgresql:16.4.0
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=mangas_api
        volumes:
            - mangas_api_db_data:/bitnami/postgresql

volumes:
    mangas_api_db_data: